disabled_rules:
  - trailing_whitespace
  - identifier_name
  - inclusive_language
  - multiple_closures_with_trailing_closure
  - for_where
  - type_name
  - block_based_kvo
  - empty_count
opt_in_rules:
  - empty_string
excluded:
  - Carthage
  - Pods
  - SwiftLint/Common/3rdPartyLib
  - .build
line_length:
    warning: 5000
    error: 15000
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 3000
    error: 5000
function_parameter_count:
    warning: 10
    error: 20
type_body_length:
    warning: 20000
    error: 50000
file_length:
    warning: 3000
    error: 5000
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 200
    error: 1000
reporter: "xcode"
